// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var Band, DataBand, FooterBand, Runtime, base,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  base = require('./base');

  Runtime = require('./runtime');

  Band = (function(superClass) {
    extend(Band, superClass);

    Band.getClassName = function() {
      return 'Band';
    };

    function Band(parent) {
      Band.__super__.constructor.call(this, parent);
      this.canBreak = false;
    }

    Band.prototype.render = function(page) {
      return console.log('rendering...');
    };

    return Band;

  })(base.BaseObject);

  DataBand = (function(superClass) {
    extend(DataBand, superClass);

    DataBand.getClassName = function() {
      return 'DataBand';
    };

    function DataBand(parent) {
      DataBand.__super__.constructor.call(this, parent);
      this.maxRows = 0;
      this.rowCount = 1;
      this.data = null;
    }

    DataBand.prototype._calcHeight = function() {
      return this.height;
    };

    DataBand.prototype.render = function(page) {
      var c, child, h, i, j, k, l, len, len1, len2, ref, ref1, ref2, results, results1, row, rows;
      if (this.data) {
        rows = this.data;
      } else if (this.rowCount) {
        rows = (function() {
          results = [];
          for (var i = 1, ref = this.rowCount; 1 <= ref ? i <= ref : i >= ref; 1 <= ref ? i++ : i--){ results.push(i); }
          return results;
        }).apply(this);
      }
      c = 0;
      results1 = [];
      for (j = 0, len = rows.length; j < len; j++) {
        row = rows[j];
        c++;
        if (this.name) {
          page.document.engine.scope[this.name] = this;
        }
        page.document.engine.scope['row'] = c;
        ref1 = this.children;
        for (k = 0, len1 = ref1.length; k < len1; k++) {
          child = ref1[k];
          child.render(page);
        }
        h = this._calcHeight();
        if ((h + page._y) > page._maxHeight) {
          page = page.newPage(page);
        }
        ref2 = this.children;
        for (l = 0, len2 = ref2.length; l < len2; l++) {
          child = ref2[l];
          page.addObject(child._obj);
          delete child._obj;
        }
        results1.push(page._y += this._calcHeight());
      }
      return results1;
    };

    return DataBand;

  })(Band);

  FooterBand = (function(superClass) {
    extend(FooterBand, superClass);

    function FooterBand() {
      return FooterBand.__super__.constructor.apply(this, arguments);
    }

    FooterBand.getClassName = function() {
      return 'FooterBand';
    };

    return FooterBand;

  })(Band);

  Runtime.registerComponent(Band);

  Runtime.registerComponent(DataBand);

  module.exports = {
    Band: Band,
    DataBand: DataBand
  };

}).call(this);

//# sourceMappingURL=band.js.map
