// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var ChildBand, GroupFooter, GroupHeader, Runtime,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ChildBand = require('./band').ChildBand;

  GroupHeader = (function(superClass) {
    extend(GroupHeader, superClass);

    GroupHeader.getClassName = function() {
      return 'GroupHeader';
    };

    function GroupHeader(parent) {
      GroupHeader.__super__.constructor.call(this, parent);
      this._printBefore = true;
    }

    GroupHeader.prototype.parentNotification = function(band, page) {
      var engine, v;
      engine = page.document.engine;
      v = engine.scope.$eval(this.expression);
      if (this._curData !== v) {
        page = this.render(page);
        this._curData = v;
      }
      return page;
    };

    return GroupHeader;

  })(ChildBand);

  GroupFooter = (function(superClass) {
    extend(GroupFooter, superClass);

    function GroupFooter() {
      return GroupFooter.__super__.constructor.apply(this, arguments);
    }

    GroupFooter.getClassName = function() {
      return 'GroupFooter';
    };

    GroupFooter.prototype.parentNotification = function(band, page) {};

    return GroupFooter;

  })(ChildBand);

  Runtime = require('./runtime');

  Runtime.registerComponent(GroupHeader);

  Runtime.registerComponent(GroupFooter);

}).call(this);

//# sourceMappingURL=group.js.map
