// Generated by CoffeeScript 1.10.0
(function() {
  var HtmlExport;

  HtmlExport = (function() {
    function HtmlExport(document) {
      this.document = document;
      this._y = 0;
      this._x = 0;
    }

    HtmlExport.prototype.toHtml = function() {
      var i, len, page, ref, s;
      s = '';
      ref = this.document.pages;
      for (i = 0, len = ref.length; i < len; i++) {
        page = ref[i];
        s += this.renderPage(page);
      }
      return s;
    };

    HtmlExport.prototype.renderObject = function(obj) {
      return obj.target.toHtml(obj);
    };

    HtmlExport.prototype.renderPage = function(page) {
      var i, len, obj, ref, s;
      s = '<div class="ng-report-print-page" style="';
      s += 'height:' + page.height.toString() + 'px;width:' + page.width.toString() + 'px;';
      s += '">';
      this._y += page.height;
      ref = page.children;
      for (i = 0, len = ref.length; i < len; i++) {
        obj = ref[i];
        s += this.renderObject(obj);
      }
      s += '</div>';
      return s;
    };

    return HtmlExport;

  })();

  module.exports = HtmlExport;

}).call(this);

//# sourceMappingURL=html.js.map
