// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var Report, Runtime, _bootstrap, loadReport, ngReport, showReport, viewer;

  Runtime = require('./runtime');

  Report = require('./report').Report;

  viewer = require('./viewer');

  ngReport = angular.module('ngReport', []);

  _bootstrap = function(el) {
    if (!el) {
      el = angular.element(Runtime.reportElement);
    }
    angular.bootstrap(el, ['ngReport']);
    el.injector().invoke(function($interpolate) {
      return Runtime.interpolate = $interpolate;
    });
    return Runtime.scope = el.scope();
  };

  loadReport = function(el, file) {
    var doc, rep;
    el = _bootstrap(el);
    rep = new Report(el);
    rep.load(file);
    doc = rep.prepare();
    return doc;
  };

  showReport = function(el, rep, viewerType) {
    var doc, v;
    doc = loadReport(el, rep);
    if (viewerType === 'pdf') {
      v = new viewer.PDFViewer(doc);
    } else {
      v = new viewer.HtmlViewer(doc, el);
    }
    return v.show();
  };

  document.loadReport = loadReport;

  window.showReport = showReport;

}).call(this);

//# sourceMappingURL=ngReport.js.map
