// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var Page, PaperSize, PreparedPage, base,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  base = require('./base');

  PaperSize = require('./report').PaperSize;

  Page = (function(superClass) {
    extend(Page, superClass);

    function Page(parent) {
      Page.__super__.constructor.call(this, parent);
      this.report = parent;
      this.marginBottom = 0;
      this.marginLeft = 0;
      this.marginTop = 0;
      this.marginRight = 0;
      this.landscape = false;
      this.width = PaperSize.A4.x;
      this.height = PaperSize.A4.y;
    }

    Page.prototype._build = function(document) {
      return new PreparedPage(document, this);
    };

    Page.prototype.clearCache = function() {
      var child, i, len, ref, results;
      Page.__super__.clearCache.call(this);
      ref = this.children;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        child = ref[i];
        results.push(child.clearCache());
      }
      return results;
    };

    Page.prototype.render = function(document) {
      var child, i, len, page, ref;
      page = this._build(document);
      document.addPage(page);
      ref = this.children;
      for (i = 0, len = ref.length; i < len; i++) {
        child = ref[i];
        child.render(page);
      }
      return page;
    };

    return Page;

  })(base.BaseObject);

  module.exports = Page;

  PreparedPage = require('./engine').PreparedPage;

}).call(this);

//# sourceMappingURL=page.js.map
