// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var Runtime;

  Runtime = (function() {
    function Runtime() {}

    Runtime.components = {};

    Runtime.getComponent = function(name) {
      return this.components[name];
    };

    Runtime.registerComponent = function(comp) {
      return this.components[comp.getClassName()] = comp;
    };

    Runtime.registerFormat = function(format) {
      return this.formats[format.getClassName()] = format;
    };

    return Runtime;

  })();

  module.exports = Runtime;

  require('./report');

  require('./group');

  require('./text');

  require('./total');

}).call(this);

//# sourceMappingURL=runtime.js.map
